name: Workflow Demo

on: 
  push

env:
  ACCESS_ID_1: ${{ vars.ACCESS_ID }}
  #ACCESS_ID: ${{ secrets.ACCESS_ID }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Echo ACCESS_ID
      run: |
          echo "ACCESS_ID=$ACCESS_ID"
          #echo "ACCESS_ID_1=$ACCESS_ID_1"
